[package]
name = "makeframes"
version = "0.0.0"
entrypoint = "src/lib.typ"
authors = ["Marc Thieme"]
license = "MIT"
description = "Beautiful, flexible, integrated. Display custom frames for theorems, environments, etc. Attractive visuals and a syntax which blends into the source seemlessly."
