[package]
name = "theorems"
version = "0.0.0"
entrypoint = "src/lib.typ"
authors = ["Marc Thieme"]
license = "MIT"
description = "Display formatted and boxed theorems, definitions and co. with custom colors and headlines."
